### ISSUE TITLE
Добавить выгрузку артефактов для тестового окружения.

### ISSUE THREAD

**Issue by vedorofeev** [egal/gitlab-ci#3]
При деплое с динамическим назначением портов контейнеров удобно выгружать список контейнеров в артефакты.
Поэтому предлагаю добавить для тестового окружения:

```yaml
upload-artifacts:deploy:
  extends: .template
  stage: deploy
  needs:
    - rabbitmq:deploy
    - postgres:deploy
  script:
    - docker-compose ps > docker-ps.log
    - rsync ./docker-ps.log ${CI_PROJECT_DIR}
  artifacts:
    paths:
      - docker-ps.log
```
